services:
  - type: web
    name: exoplanet-frontend
    env: static
    buildCommand: bun install && bun run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
